global.window={};
window.RMSLiterature={};
require("../assets/literature.js");require("../assets/methods.js");require("../assets/analytics.js");require("../assets/writing.js");
window.RMSCoach={reviewStage:(id,p)=>({score:80,label:"Developing",messages:[]})};
require("../assets/journey.js");
const L=window.RMSLiterature,M=window.RMSMethods,S=window.RMSAnalytics,W=window.RMSWriting,J=window.RMSJourney;
function base(){return {name:"Simulation",created:"2026-09-04",ready:{},data:{},sources:[],schema:[],methods:{},analysis:{},writing:{},journey:{}}}
// Experimental nonhuman project
let p=base();p.data.finalRQ="How does salt concentration affect seed germination?";p.data.designType="Experimental";L.normalizeProject(p);M.normalizeProject(p);S.normalizeProject(p);W.normalizeProject(p);J.normalizeProject(p);
p.methods.constructs=[{name:"salt",role:"Manipulated independent variable",operational:"0% vs 1%"},{name:"germination",role:"Outcome / dependent variable",operational:"germinated by 72 h"}];p.methods.conditions=[{name:"0%",definition:"water"},{name:"1%",definition:"salt"}];p.methods.design={experimentalUnit:"dish",assignment:"Random assignment",sameUnitAllConditions:"no",primaryOutcome:"proportion germinated",independentUnits:"8",rowUnit:"dish"};p.methods.sampling={population:"seeds of this batch",sample:"8 dishes",method:"Convenience sample",generalization:"similar batch"};p.methods.measurements=[{construct:"germination",instrument:"visual check",operational:"radicle visible",scale:"binary",timing:"72 h",reliability:"same rule",validity:"direct germination criterion"}];p.methods.ethics={humanParticipants:"no",storage:"school drive"};p.methods.procedureSteps=[{action:"randomly assign dishes",record:"assignment"},{action:"apply solutions",record:"solution"},{action:"score germination",record:"count"}];p.schema=[{name:"dish_id",type:"ID",definition:"dish"},{name:"condition",type:"Categorical",definition:"salt"},{name:"germinated",type:"Count",definition:"count"}];let mr=M.readiness(p);if(mr.critical)process.exit(1);
// Observational project must preserve noncausal boundary in writing audit
let q=base();q.data.finalRQ="What is the relationship between sleep and grades?";q.data.designType="Correlational / observational";q.writing.sections={introduction:"Prior evidence is summarized.",literature:"Prior evidence is summarized.",method:"Sleep and grades were measured.",results:"Sleep was associated with grades, r = .40, p = .03.",discussion:"The association may reflect confounding and cannot establish causation. A limitation is self-report.",conclusion:"Sleep was associated with grades in this sample.",abstract:"This correlational study measured sleep and grades. The variables were positively associated. Causation cannot be inferred."};q.analysis.runs=[{timestamp:new Date().toISOString(),structure:"correlation",output:{test:"Pearson correlation"},neutral_summary:"association",assumption_notes:[],configuration:{}}];q.methods.protocolVersions=[{}];W.normalizeProject(q);let wa=W.paperAudit(q);if(wa.issues.some(x=>/causal claim ceiling violation/i.test(x[1])))process.exit(1);
// Unsafe human intervention must stop
let u=base();u.data.finalRQ="Does sleep deprivation improve study time?";u.data.designType="Experimental";M.normalizeProject(u);u.methods.ethics={humanParticipants:"yes",intervention:"yes",procedureRisk:"sleep deprivation",consent:"planned",withdrawal:"planned",storage:"planned"};if(M.ethicsRoute(u).status!=="do_not_facilitate")process.exit(1);
console.log("PASS end-to-end pathway simulations");